version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo-test
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - /home/greg/Development/docker/mongo:/var/lib/mongo/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-test
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://admin:123@mongo-test:27017/